/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ViewportDragDrop.view.MainView', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                me.processWestTabPanel({
                    xtype: 'tabpanel',
                    region: 'west',
                    split: true,
                    width: 300,
                    suspendLayout: true,
                    title: 'West Tab Panel',
                    activeTab: 0,
                    deferredRender: false,
                    items: [
                        {
                            xtype: 'form',
                            bodyPadding: 10,
                            title: 'Tab 1',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'My Panel'
                        }
                    ]
                }),
                me.processNorthRegionPanel({
                    xtype: 'panel',
                    region: 'north',
                    split: true,
                    height: 175,
                    collapsible: true,
                    title: 'North Region Panel'
                }),
                me.processCenterFormPanel({
                    xtype: 'form',
                    region: 'center',
                    bodyPadding: 10,
                    title: 'Center Form Panel',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Label'
                        }
                    ]
                }),
                me.processEastTreeGridPanel({
                    xtype: 'treepanel',
                    collapseMode: 'mini',
                    region: 'east',
                    split: true,
                    width: 200,
                    collapsible: true,
                    title: 'East Tree Grid Panel',
                    viewConfig: {

                    },
                    columns: [
                        {
                            xtype: 'treecolumn',
                            dataIndex: 'text',
                            text: 'Nodes',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'value',
                            text: 'Value'
                        }
                    ]
                }),
                me.processSouthPanel({
                    xtype: 'panel',
                    region: 'south',
                    split: true,
                    height: 175,
                    collapsible: true,
                    title: 'South Panel'
                })
            ]
        });

        me.callParent(arguments);
    },

    processWestTabPanel: function(config) {
        var ddr = Ext.create('Ext.ux.DragDropRegion', {
            drag: true,
            drop: true,
            group: 'ewGroup'
        }) 


        config.plugins = [ddr]
        return config;
    },

    processNorthRegionPanel: function(config) {
        config.plugins = [Ext.create('Ext.ux.DragDropRegion')]
        return config;
    },

    processCenterFormPanel: function(config) {
        config.plugins = [Ext.create('Ext.ux.DragDropRegion')]
        return config;
    },

    processEastTreeGridPanel: function(config) {
        var ddr = Ext.create('Ext.ux.DragDropRegion', {
            drag: true,
            drop: true,
            group: 'ewGroup'
        }) 


        config.plugins = [ddr]
        return config;
    },

    processSouthPanel: function(config) {
        var ddr = Ext.create('Ext.ux.DragDropRegion', {
            drag: true,
            drop: true,
            group: 'ewGroup'
        });

        config.plugins = [ddr];

        return config;
    }

});